[pytest]
addopts =
## General
    -v
    #--browser=chromium
    #--browser-name=chromium
    --headed
    #--base-url=http://localhost/opencart/upload
    # --base-url=https://tutorialsninja.com/demo/
     --base-url=https://naveenautomationlabs.com/opencart


# https://playwright.dev/python/docs/test-runners


## Captures and report (Debugging)
    #--video=retain-on-failure
    --video-mode=retain-on-failure
    # video=on
    #--screenshot=only-on-failure
    --screenshot-mode=only-on-failure
    #--screenshot=on
    #--tracing=retain-on-failure
    --trace-mode=retain-on-failure
    #--tracing=on
    #--html=reports/myreport.html --selfcontained-html --capture=tee-sys
    --alluredir=reports/allure-results
    

## Parallel Execution
    #-n1=1
    #--numprocesses=2
                    # will run in parallel 2 tests



### Flaky Test Handling
    #--reruns 2
    #--reruns-dalay 2




## Test Grouping (Markers)
    ## only one command when running pytest
    -m "sanity"         
                        # will run only sanity marked tests

    ######   specified this we can run only pytest ./tests/
    #-m "regression"
    #-m "sanity or regression"
    #-m "sanity and regression"
    #-m "sanity and not regression"
    #-m "regression and not sanity"

    #-m "datadriven"
    #-m "end_to_end"


### Custom Markers
markers = 
    sanity: basic quick check                # Marks a sanisy test (basic quick check)
                        #poți deschide aplicația
                        #login funcționează
                        #poți face o comandă simplă
                        #search funcționează

    regression:                 # Marks a regrsssion test (full end_to_end validation)
                        #login (all cases)
                        #register
                        #search
                        #add to cart
                        #checkout
                        #edge cases
                        #validate


    datadriven: Marks datadriven test
    end_to_end: Full end_to end test